### ISSUE TITLE
Investigate Python GUI libraries and choose one

### ISSUE THREAD

**Issue by YuriNeverov** [YuriNeverov/Tic-Tac-Toe#5]
There is probably more than one Python GUI library. One of them is of course `tkinter`. But also we should investigate other open-source libraries, consider their pros and cons. This issue requires report in comments, no actual code is required.

**Comment by RazO0m** [comment]
Tkinter.


Advantages:

- Tkinter is part of most Python installations, which makes it easier to get started without having to install any additional packages.

- As easy to learn and use as possible.

- Cross-platform

- Has detailed and accessible documentation.

- Contains two powerful widgets - Text (multiline text field with formatting support) and Canvas ("canvas" on which you can draw and display any graphic objects).

- Includes the ttk module, which provides the developer with a set of additional widgets - Combobox, Notebook, Treeview, Progressbar, Scale and others.

- Allows you to make the interface adaptive.

- Suitable for beginners


Disadvantages:

- Graphical interfaces created using Tkinter look outdated.

- Tkinter has decent performance for small and medium-sized applications. However, problems may arise with large projects or applications that require a quick update of the user interface.

**Comment by YuriNeverov** [comment]
Please note that we also want to use something like buttons. I.e. we want to click on canvas and know position of that click, which is later would be converted into in-board-position and then converted to move

**Comment by RazO0m** [comment]
PyQt


Advantages:

- Cross-platform

- Known for its flexibility, wide capabilities and reliability. It is suitable for large projects and professional applications.

- He has comprehensive documentation, and his community is growing. Since PyQt is based on the Qt framework platform, you can find extensive resources related to Qt development that can be useful at work.

- offers a wide range of additional features, such as custom widgets, integration with OpenGL, multithreading support and extensive layout management. It is suitable for complex applications and professional projects where advanced functionality is required.

- PyQt applications have their own appearance on all supported platforms, which makes them visually attractive and compatible with the user OS. PyQt also provides advanced style settings that allow extensive customization.


Disadvantages:
- PyQt requires a separate installation using pip (for example, pip install PyQt5). A compatible version of the Qt library must also be installed on the system.

**Comment by RazO0m** [comment]
wxPython


Advantages:

- cross-platform

- lightness compared to PyQt

- Has its own appearance on all supported platforms, which makes them visually attractive and compatible with the user OS

- High productivity


Disadvantages:

- requires a separate installation

**Comment by RazO0m** [comment]
@YuriNeverov I think we should try PyQt, what do you think?

**Comment by YuriNeverov** [comment]
> @YuriNeverov I think we should try PyQt, what do you think?

Does it support mouse click positions?

**Comment by RazO0m** [comment]
> > @YuriNeverovЯ думаю, мы должны попробовать PyQt, что вы думаете?
> 
> Поддерживает ли он позиции щелчка мыши?

Yes, PyQt has a wide range of features

**Comment by YuriNeverov** [comment]
Ok, let's choose PyQt then
